/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cs245project.JPanels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ningl_000
 */
public class SudokuBoardDisplay extends JPanel implements ActionListener {
        
    public interface SudokuGameStateListener{
        public void onSubmitButtonPressed(int score);
        public void onCancelButtonPressed(int score);
    }
    public void setSudokuGameStateListener(SudokuGameStateListener l){
        sudokuListener = l;
    }
    
    private SudokuGameStateListener sudokuListener;
    SudokuJPanel sudoku;   
    private JLabel name;
    private JLabel time;
    private JButton submit;
    private JButton cancel;
    private int finalScore = 0;
    /**
     * Creates new form SudokuBoardDisplay
     */
    public SudokuBoardDisplay() {
        super();
        initComponents();
        mInit();
        this.setBounds(0,0,600,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void mInit() {
        sudoku = new SudokuJPanel();
        //add(sudoku);
        name = new JLabel();
        time = new JLabel();
        submit = new JButton();
        cancel = new JButton();
        name.setText("Sudoku");
        name.setBounds(0,0,100,100);
        time.setBounds(400,50,150,40);
        submit.setText("Submit");
        cancel.setText("Cancel");
        submit.setBounds(10, 450, 50, 40);
        cancel.setBounds(540, 450, 50, 40);
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if(sudokuListener!=null){
                    sudokuListener.onSubmitButtonPressed(finalScore);
                }
            }
        });
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if(sudokuListener!=null){
                    sudokuListener.onCancelButtonPressed(finalScore);
                }
            }
        });
        add(name);
        add(submit);
        add(cancel);
        revalidate();
        repaint();
    }

    public void setScore(int score){
        finalScore = score;
    }
    
    @Override
    public void actionPerformed(ActionEvent ae) {
        time.setText(new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()) );
    }
}
