/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245project.JPanels;

import cs245project.JPanels.GameOfColorJPanel;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Stroke;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ningli
 */
public class SudokuJPanel extends JPanel {

    private final int startScore = 540;
    private int finalScore;
    private int gridSize = 9;
    private int subGridSize = 3;
    private int cellSize = 0;
    private int boxWidth = cellSize * gridSize;
    private int boxHeight = cellSize * gridSize;
    private Color textColor = Color.BLACK;
    private Color inputColor = Color.RED;
    private Font numbersFont = new Font("MonoSpaced", Font.BOLD, 20);
    
    private JTextField[][] cells = new JTextField[gridSize][gridSize];
    private int[][] puzzle =
        {{8, 3, 5, 4, 1, 6, 9, 2, 7},
        {2, 9, 6, 8, 5, 7, 4, 3, 1},
        {4, 1, 7, 2, 9, 3, 6, 5, 8},
        {5, 6, 9, 1, 3, 4, 7, 8, 2},
        {1, 2, 3, 6, 7, 8, 5, 4, 9},
        {7, 4, 8, 5, 2, 9, 1, 6, 3},
        {6, 5, 2, 7, 8, 1, 3, 9, 4},
        {9, 8, 1, 3, 4, 5, 2, 7, 6},
        {3, 7, 4, 9, 6, 2, 8, 1, 5}};
    private boolean[][] blank =
        {{false,true,true,  false,true,false, true,true,false},
         {true,true,true,  true,true,true,  false,true,true},
         {true,false,true,  true,true,true,  false,false,true},
         
         {false,true,false,  true,false,true,  false,false,true},
         {true,true,true,  true,false,true,  true,true,true},
         {true,false,false,  true,false,true,  false,true,false},
         
         {true,false,false,  true,true,true,  true,false,true},
         {true,true,false,  true,true,true,  true,true,true},
         {false,true,true,  false,true,false,  true,true,false}};

    /**
     * Creates new form SudokuJPanel
     */
    public SudokuJPanel() {
        super();
        initComponents();
        setLayout(new GridLayout(gridSize, gridSize));
        for(int row = 0; row < gridSize; row++){
            for(int col = 0; col < gridSize; col++){
                cells[row][col] = new JTextField();
                add(cells[row][col]);
                if(blank[row][col]){
                    cells[row][col].setText("");
                    cells[row][col].setEditable(true);
                    cells[row][col].setBackground(java.awt.Color.white);
                } else {
                    cells[row][col].setText(puzzle[row][col] + "");
                    cells[row][col].setEditable(false);
                    cells[row][col].setBackground(java.awt.Color.white);
                    cells[row][col].setForeground(java.awt.Color.black);
                }
                cells[row][col].setHorizontalAlignment(JTextField.CENTER);
                cells[row][col].setFont(numbersFont);
            }
        }
        setPreferredSize(new Dimension(350, 380));
        setVisible(true);
    }
    
  
    
    public void mInit(){
        /*for(int row = 0; row < gridSize; row++){
            for(int col = 0; col < gridSize; col++){
                cells[row][col] = new JTextField();
                board.add(cells[row][col]);
                if(blank[row][col]){
                    cells[row][col].setText("");
                    cells[row][col].setEditable(true);
                    cells[row][col].setBackground(java.awt.Color.white);
                } else {
                    cells[row][col].setText(puzzle[row][col] + "");
                    cells[row][col].setEditable(false);
                    cells[row][col].setBackground(java.awt.Color.white);
                    cells[row][col].setForeground(java.awt.Color.black);
                }
                cells[row][col].setHorizontalAlignment(JTextField.CENTER);
                cells[row][col].setFont(numbersFont);
            }
        }
        board.setPreferredSize(new Dimension(boxWidth, boxHeight));
        setVisible(true);*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setScore(int score){
        finalScore = score + startScore;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
